### ISSUE TITLE
Set goal for which classes we need to do the project : 9th and 11th (Decision)

### ISSUE THREAD

**Issue by jatin-sandhuria** [jatin-sandhuria/Government-School-Social-Project-India#9]

**Comment by ridhi999** [comment]
Board classes specifically class 10 (not if class 5 is also a board class as they are too young for it)

**Comment by jatin-sandhuria** [comment]
Neha - 
nav chetna - Kids
PPT - officials
an online session

survey - need to know what kind of problems kids have. eg. if the 12th class kid might have financial problems. (for all the kids in the school)

**Comment by jatin-sandhuria** [comment]
1/20/2018: Decision made that we will go with 9th and 11th class.
